### ISSUE TITLE
E: Problem executing scripts DPkg::Post-Invoke '/usr/libexec/apparmor-profile-everything/grub-cfg'

### ISSUE THREAD

**Issue by zqpvr** [Kicksecure/apparmor-profile-everything#76]
I keep getting this error E: Problem executing scripts DPkg::Post-Invoke '/usr/libexec/apparmor-profile-everything/grub-cfg' after installing apparmor-profile-everything and trying to install apparmor-profiles-kicksecure

**Comment by adrelanos** [comment]
For debugging please post the output of:

    sudo /usr/libexec/apparmor-profile-everything/grub-cfg

But please post it in https://forums.whonix.org/t/apparmor-for-complete-system-including-init-pid1-systemd-everything-full-system-mac-policy/8339 since github isn't used for issue tracking.
